### Get all events
GET http://localhost:3000/members

### Get member by id
GET http://localhost:3000/members/50d1821b-0c61-4667-b324-bad5998b1111

### Get member by id that doesn't exist will return not found
GET http://localhost:3000/members/ABC

### Add Member with invalid fields will return an error
POST http://localhost:3000/members
Content-Type: application/json

{
    "name": "Bob"
}

### Add Member with invalid fields will return an error
POST http://localhost:3000/members
Content-Type: application/json

{
    "memberName": "Bob",
    "status": "active"
}

### Add Member with invalid joined date will return an error
POST http://localhost:3000/members
Content-Type: application/json

{
    "memberName": "Bob",
    "status": "active",
    "joinedDate": "ABC"
}

### Add Member with valid fields but without joinedDate
POST http://localhost:3000/members
Content-Type: application/json

{
    "memberName": "Bobby",
    "status": "active"
}

### Add Member with valid fields with joinedDate
POST http://localhost:3000/members
Content-Type: application/json

{
    "memberName": "Khris",
    "status": "active",
    "joinedDate": "2021-08-07 17:30:00"
}

### Update Member with valid fields
PUT http://localhost:3000/members/efd99f45-951f-4cc7-a09f-6532737c86a5
Content-Type: application/json

{
    "memberId": "efd99f45-951f-4cc7-a09f-6532737c86a5",
    "memberName": "Bry",
    "status": "active",
    "joinedDate": "2021-10-30 15:30:00"
}

### Update Member with missing fields will fail
PUT http://localhost:3000/members/efd99f45-951f-4cc7-a09f-6532737c86a5
Content-Type: application/json

{
    "memberId": "efd99f45-951f-4cc7-a09f-6532737c86a5",
    "joinedDate": "2021-10-30 15:30:00"
}

### Update Member with different id will return an error
PUT http://localhost:3000/members/04b86bf8-1069-4988-bc2f-bb35d8744f9e
Content-Type: application/json

{
    "memberId": "04b86bf8-1069-4988-bc2f-bb35d8744f9e",
    "memberName": "Bry",
    "status": "active",
    "joinedDate": "2021-10-30 15:30:00"
}
